### ISSUE TITLE
It would be nice to add the possibility of money between worlds to the plugin

### ISSUE THREAD

**Issue by CuBeR116** [Patfreeze/themultiwordmoney#1]
At the moment, players need to be in the same world to transfer money. It would be great if you could transfer money if the players are in the same group at the moment.

Also, add the ability to transfer money if the players are in different groups, but with an additional option:
/pay [Player] [Amount] [Group]

**Comment by Patfreeze** [comment]
Hi,

The main idea of this plugin is to separate economy between worlds without installing more servers.
I will check if I can do something to detect, if or not, the players are in the same group and not the same world.

You can grab all the code and make an alternative of mine if you like. I've not much time to make new feature at the moment.
