### ISSUE TITLE
Plugin conflict with zAuctionHouse

### ISSUE THREAD

**Issue by CuBeR116** [Patfreeze/themultiwordmoney#3]
If the auction plugin [zAuctionHouse] is installed, then it stops working, because. themultiwordmoney intercepts his commands.

**Comment by Patfreeze** [comment]
Could you give me the version of themultiwordmoney you are using. I know that I made a new version to disabled shop and auction. Maybe I break something.

**Comment by Patfreeze** [comment]
Removed the Auction from the plugin, this will fix your issue
